config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :users
  get "my_portfolio", to: 'users#my_portfolio'
  post 'search_stock', to: 'stocks#search'#, defaults: { format: :turbo_stream }
  get 'my_friends', to: 'users#show_friends'
  resources :friendships
  get 'my_friends', to: 'users#show_friends'
  post 'search_friends', to: 'users#search'#, defaults: { format: :turbo_stream }
  resources :users, only: [:show]

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1')
    begin
      new(ticker: ticker_symbol, name:client.company(ticker_symbol).company_name ,last_price:  client.price(ticker_symbol)  )
    rescue => exception
      return nil

    end


  end
  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    p params
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock == nil
        respond_to do |format|
          flash.now[:alert] = "Enter a valid Stock"
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(:messagess, partial: "layouts/messages"),
              turbo_stream.update(:formUpdate, partial: "stocks/searchform", locals: {stock: "asdsda"})
            ]
          end
          #format.turbo_stream { render turbo_stream: turbo_stream.update(:idteste, partial: "users/result")}
          #format.html { render root_path, alert: "Please enter a valid symbolaa"} ## Specify the format in which you are rendering "new" page
        end
      else
        #render "users/my_portfolio"

        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(:idteste, partial: "users/result"),
              turbo_stream.update(:formUpdate, partial: "stocks/searchform", locals: {stock: "Asdasd"})
            ]
            #format.html { render 'users/my_portfolio'} ## Specify the format in which you are rendering "new" page
          end
        end
        #render 'users/my_portfolio'
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Enter a Stock"
        format.turbo_stream { render turbo_stream: turbo_stream.update(:messagess, partial: "layouts/messages")}
        #format.html { render 'users/my_portfolio'} ## Specify the format in which you are rendering "new" page
      end
    end
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/ .turbo_stream.erb
<%= turbo_stream.prepend "results" do %>
  <%= render "users/result" %>
<% end %>

app/views/stocks/_list.html.erb
<table class="table table-bordered table-hover">

  <thead>
  <tr>
    <th scope="col">Ticker</th>
    <th scope="col">Name</th>
    <th scope="col">Price</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @tracked_stocks.each do |stock| %>
    <tr>
      <th scope="row"><%= stock.ticker %></th>
      <td><%= stock.name %></td>
      <td><%= stock.last_price %></td>
      <td><%= link_to "Delete", user_stock_path(stock),
                      data:{turbo_method: :delete},
                      class:"btn btn-danger" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/stocks/_searchform.html.erb
<%= form_tag search_stock_path, remote: true, method: :post do  %>
  <div class="d-flex justify-content-center form-group row ">
    <div class="col-sm-8">
      <div class="input-group mb-3 mt-5">
        <%= text_field_tag :stock,nil, class:"form-control form-control-lg", placeholder:"Stock ticker symbol", autofocus:true%>
        <%= button_tag type: :submit, class: "btn btn-success" do%>
          <%= stock %>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/stocks/search.html.erb
<%= @stock %>

app/views/stocks/search.turbo_stream.erb
<%= turbo_stream.prepend "results" do %>
  <%= render partial: "users/result" %>
<% end %>