config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :users
  get "my_portfolio", to: 'users#my_portfolio'
  post 'search_stock', to: 'stocks#search'#, defaults: { format: :turbo_stream }
  get 'my_friends', to: 'users#show_friends'
  resources :friendships
  get 'my_friends', to: 'users#show_friends'
  post 'search_friends', to: 'users#search'#, defaults: { format: :turbo_stream }
  resources :users, only: [:show]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    current_user.stocks.include?
  end

  def under_stock_limit?
    current_user.stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit?
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = first_name_matches(param) + last_name_matches(param) + email_matches(param)
    to_send_back.uniq!
    return nil if to_send_back.empty?
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, string)
    User.where("#{field_name} like ?", "%#{string}")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id}
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

  def show_friends
    @users = current_user.friends
  end

  def search
    if params[:user].present?
      @user = User.search(params[:user])
      @user = current_user.except_current_user(@user)
      p @user
      if @user
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(:idteste1, partial: "users/friend_result"),
              turbo_stream.update(:searchfriends, partial: "users/search_friends_form")
            ]
          end
        end
      else
        respond_to do |format|
          flash.now[:alert] = "No user found"
          format.turbo_stream do
            render turbo_stream: [
              turbo_stream.update(:searchfriends, partial: "users/search_friends_form"),
              turbo_stream.update(:messagess, partial: "layouts/messages")
            ]
            #format.html { render 'users/my_portfolio'} ## Specify the format in which you are rendering "new" page
          end
        end
      end
      else
    respond_to do |format|
      flash.now[:alert] = "Enter a name"
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update(:searchfriends, partial: "users/search_friends_form"),
          turbo_stream.update(:messagess, partial: "layouts/messages")
        ]
        #format.html { render 'users/my_portfolio'} ## Specify the format in which you are rendering "new" page
      end
    end
    end

  end


  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks

  end

end

app/helpers/users_helper.rb
module UsersHelper
  def can_be_friend?(user_id)
    !(current_user.friends.include? User.find(user_id))
  end


  def can_buy_stock?(ticker)
    !(current_user.stocks.include? Stock.find_by_ticker(ticker))
  end

end

app/views/users/_friend_result.html.erb
<% if @user %>
  <% @user.each do |user|%>
    <div class="d-flex justify-content-center ">
      <div class="card card-header results-block">
        <strong>Email: </strong><%=user.email %>
        <strong>Name: </strong><%=user.first_name %>
        <strong>Actions: </strong><%="@user.last_price" %>
      </div>
      <% if can_be_friend?(user.id) == true %>
        <%= link_to "Add", friendships_path(id: user.id), class:"btn btn-primary btn-lg", data:{turbo_method: :post}%>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/_list_friends.html.erb
<table class="table table-bordered table-hover">

  <thead>
  <tr>
    <th scope="col">Email</th>
    <th scope="col">First Name</th>
    <th scope="col">Last Name</th>
    <th scope="col">Profile</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.email %></th>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= link_to "Profile", user_path(user), class:"btn btn-success" %></td>
      <td><%= link_to "Stop following", friendship_path(user),
                      data:{turbo_method: :delete},
                      class:"btn btn-danger" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/_result.html.erb
<%= Time.zone.now %>

<% if @stock %>
  <div class="d-flex justify-content-center ">
    <div class="card card-header results-block">
      <strong>Symbol: </strong><%=@stock.ticker %>
      <strong>Name: </strong><%=@stock.name %>
      <strong>Price: </strong><%=@stock.last_price %>
    </div>
    <% if can_buy_stock?(@stock.ticker) == true %>
      <%= link_to "Add", user_stocks_path(user: current_user, ticker: @stock.ticker), class:"btn btn-primary btn-lg", data:{turbo_method: :post}%>
    <% end %>
  </div>
<% end %>

app/views/users/_search_friends_form.html.erb
<%= form_tag search_friends_path, remote: true, method: :post do  %>
  <div class="d-flex justify-content-center form-group row ">
    <div class="col-sm-8">
      <div class="input-group mb-3 mt-5">
        <%= text_field_tag :user,nil, class:"form-control form-control-lg", placeholder:"Search for a user", autofocus:true%>
        <%= button_tag type: :submit, class: "btn btn-success" do%>
          <%= "stock" %>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/users/my_portfolio.html.erb
<%= turbo_frame_tag "formUpdate" do %>
    <%= render partial: "stocks/searchform" , locals: {stock: "Search"} %>
<% end %>

<%= turbo_frame_tag "idteste" do %>
    <%= render partial: 'users/result' %>
<% end %>


<%= turbo_frame_tag "listastocks" do %>
    <%= render partial: 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>


<%= turbo_frame_tag "listastocksuser" do %>
  <%= render partial: 'stocks/list' %>
<% end %>

app/views/users/show_friends.html.erb
<%= turbo_frame_tag "searchfriends" do %>
  <%= render partial: 'users/search_friends_form' %>
<% end %>


<%= turbo_frame_tag "idteste1" do %>
  <%= render partial: 'users/friend_result' %>
<% end %>


<%= turbo_frame_tag "listafriends", target: :_top do %>
  <%= render partial: 'users/list_friends' %>
<% end %>