config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  devise_for :users
  get "my_portfolio", to: 'users#my_portfolio'
  post 'search_stock', to: 'stocks#search'#, defaults: { format: :turbo_stream }
  get 'my_friends', to: 'users#show_friends'
  resources :friendships
  get 'my_friends', to: 'users#show_friends'
  post 'search_friends', to: 'users#search'#, defaults: { format: :turbo_stream }
  resources :users, only: [:show]

end

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert <%= name=="notice"?"alert-success":"alert-danger" %> alert-dismissible fade show" role="alert">


      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Finance App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Portfolio", my_portfolio_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", my_friends_path, class:"nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
    <nav class="navbar navbar-light bg-light">
      <form class="container-fluid justify-content-start">
        <% if !user_signed_in? %>
          <%= link_to "Sign in  ", new_user_registration_path	, class: "btn btn-outline-secondary"%>
          <%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary"%>
      <% else %>


          <div  class="nav-link">
            <h5 class="ml-5">
              <i class="fa-solid fa-user"></i> <%= current_user.full_name %>
            </h5>
          </div>

          <%= link_to "Edit", edit_user_registration_path(current_user)	, class: "btn btn-outline-secondary" %>
        <%= link_to "Log out", destroy_user_session_path, class: "btn btn-outline-secondary", data:{turbo_method: :delete}%>
      <% end %>
          </form>
    </nav>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance</title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  <%# this loads Sprockets/Rails asset pipeline %>
    <%= javascript_importmap_tags %> <%#  this loads JS from importmaps %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/24bb0b182c.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= Time.zone.now %>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <div id="messagess">
        <%= render 'layouts/messages' %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>